### PR TITLE
feat(mpg123-decoder): enable gapless decoding

### PR DESCRIPTION
**Pull request by londek**
Enables gapless decoding in mpg123 meaning mpg123 from now on will trim the well-known silence aka padding+delay based on encoder metadata.

Used to grow 44.1khz 1.00.000 min long audio up to even 1.00.029 which is enough to give it a "click" when performing operations on audio files.

Compilled and tested under WSL2, works fine ;3

### CODE REVIEW

**Comment by eshaz** [comment]
This looks good, thanks for the contribution!

Could you upload a test file / example that is decoded correctly when this flag is enabled? I can add this to the unit tests.

I commit the build and dist files, so those who don't want to use npm can just download directly and use as a script tag.

**Comment by eshaz** [comment]
A few of the existing tests were failing, and some of the files didn't decode properly, so I went ahead and refactored this out into an option. It's disabled as a default to prevent any existing usage from breaking.

I'll merge this once I get an example to add to a unit test. If you don't have an example to share, please let me know how I can create one that reproduces this issue.

Thanks again for contributing!

**Comment by londek** [comment]
Hey, yeah sure thing, I can do it right now. I was busy, sorry!

**Comment by eshaz** [comment]
I expected the lengths to change, and they did; however, there are a few files that appeared to decode incorrectly. This might just be the way I'm testing it though. I'll look a bit more closely into this.

Some context on MP3:

MP3 wasn't designed with sample accurate decode lengths in mind. Essentially the official spec has no way  to store the total decoded samples of a file, nor the delay (start), and padding (end). The most basic form of MP3 is just a stream of frames with no additional metadata. The most basic form of decoding MP3 is to just decode everything and output whatever the decoder received without trimming anything.

Having said that, trimming / gapless can still be accomplished, but it's done as an unofficial addition to the original spec. These "unofficial" methods have been around for a really long time, so it's debatable if it might as well just be considered part of the spec at this point.

Here's a couple ways encoders and decoders have done this:

* [LAME docs reagarding well known padding](https://lame.sourceforge.io/tech-FAQ.txt)
* [LAMEinfo (Xing) frame](https://eyed3.readthedocs.io/en/latest/plugins/lameinfo_plugin.html)
* https://cast.readme.io/docs/mp3

If you really need guaranteed sample accurate decoding lengths, I would recommend using a different codec such as Ogg Opus. Ogg allows for the sample length accuracy and Opus is the best lossy codec to date regarding the size to perceived audio quality ratio.

**Comment by eshaz** [comment]
It looks like the differences in length on the tests were actually due to a bug in how the mpg123 decoder flags were being set. I also found a buffer size issue causing some frame decoding to truncate.

After fixing these issues, I tried to create a file that decodes differently with the gapless flag enabled using Audacity, ffmpeg, and LAME with various options, but wasn't able to find something that reproduced what you found. Every file decoded with the MP3 padding / delay present regardless of the gapless setting.

If you have an example that reproduces this, please share it, so I can make sure this is working correctly. If not I'll merge this PR with the option disabled by default.

**Comment by londek** [comment]
Hey, I was out for a weekend

`If you really need guaranteed sample accurate decoding lengths, I would not recommend using MP3.` - It is not my choice really! My personal project calls external api for processing audio and it always returns mp3, yes I am requesting api with .ogg, but there are really no meaningful advantages to doing this.

Why do I really hate gaps? When concatenating audio clips (and this is what my personal project does too under the hood) gaps are literally unpleasant to listen to.
Issue #1 with removing gaps manually is: in silent parts it's pretty hard to determine when gap ends and when it starts.
Issue #2 with removing gaps manually is: why do it manually if all software I'm using doesn't introduce gaps, this looks like a lack of feature and not really a "skill issue" (kappa).

Why it doesn't show any effect for you? I don't really know, your mp3 files have lame info tag and lame extra info present, even Reaper shows the difference when option "Correct compressor delay/latency" is checked
image
Sources:
https://lame.sourceforge.io/tech-FAQ.txt
[check_lame_tag()](https://github.com/mileswu/mpg123/blob/44792059a25532ff62679c38f1f248d41501869f/src/libmpg123/parse.c#L109) inside mpg123

So I have built the project and ran enableGapless tests, everything works fine just expected values are wrong. See how is it decoded in Reaper with `Correct compressor delay/latency` checked:
image
`44100.mono/stereo.cbr.mp3` are 1s files from what I see. Duration is roughly `samples / sampleRate`, so expected samples should be basically sampleRate (44100).

Also some tests were using .nogaps. file instead of .gaps. and the other way around.

I pushed fixes to tests and correct (gaps) expected files (basically exactly 1s long audio files).

I hope this message clears up most of miscommunication ;)

**Comment by eshaz** [comment]
I found the issue, and it was completely on my side. I wasn't running `make configure` for this one, which takes the `config.h` file and copies it into the mpg123 git submodule clone. I've refactored this out, so the same mistake can't be easily made again.

The gapless decoding is working now for me. I have a few more things to fix before merging / releasing, but I will probably have this enabled by default, now that I have it working.

**Comment by eshaz** [comment]
I've release these changes in `mpg123-decoder/1.0.0`. Thanks for contributing!

**Pull request merged**
